version: '3.4'

services:
#mongodb serice
   mongo_db:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db  

   userservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000  
    # volumes:
    #   - .:/usr/src/app  
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
